#!/usr/bin/env bash
# Print openssl commands (and optional values) for local dev secrets.
# Never writes to disk unless --write .env.local is passed explicitly.
set -euo pipefail

WRITE_FILE=""
SHOW_VALUES=0

usage() {
  cat <<'EOF'
usage: scripts/generate-local-secrets.sh [--values] [--write .env.local]

Prints openssl commands for BETTER_AUTH_SECRET, KEY_ENCRYPTION_MASTER_KEY, and
PAYMENT_WEBHOOK_SECRET (32-byte base64 each). Output goes to stdout only.

  --values          Also print generated values (still stdout; use with care)
  --write PATH      Append secrets to PATH (default: .env.local) — see warning
  -h, --help        Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --values)
      SHOW_VALUES=1
      shift
      ;;
    --write)
      WRITE_FILE="${2:-.env.local}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

gen_base64_32() {
  openssl rand -base64 32
}

BETTER_AUTH_SECRET="$(gen_base64_32)"
KEY_ENCRYPTION_MASTER_KEY="$(gen_base64_32)"
PAYMENT_WEBHOOK_SECRET="$(gen_base64_32)"

cat <<'EOF'
# Local secret generation — copy commands or values into .env (never commit)

# BETTER_AUTH_SECRET (32-byte base64)
EOF
echo "openssl rand -base64 32"

cat <<'EOF'

# KEY_ENCRYPTION_MASTER_KEY (32-byte base64)
EOF
echo "openssl rand -base64 32"

cat <<'EOF'

# PAYMENT_WEBHOOK_SECRET (32-byte base64)
EOF
echo "openssl rand -base64 32"

if [[ "$SHOW_VALUES" -eq 1 ]]; then
  cat <<EOF

# Generated values (stdout only — paste into .env manually)
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
KEY_ENCRYPTION_MASTER_KEY=${KEY_ENCRYPTION_MASTER_KEY}
PAYMENT_WEBHOOK_SECRET=${PAYMENT_WEBHOOK_SECRET}
EOF
fi

if [[ -n "$WRITE_FILE" ]]; then
  cat >&2 <<EOF
warning: writing secrets to ${WRITE_FILE} — ensure this file is gitignored and never committed.
EOF
  {
    echo ""
    echo "# Generated by scripts/generate-local-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}"
    echo "KEY_ENCRYPTION_MASTER_KEY=${KEY_ENCRYPTION_MASTER_KEY}"
    echo "PAYMENT_WEBHOOK_SECRET=${PAYMENT_WEBHOOK_SECRET}"
  } >>"$WRITE_FILE"
  echo "appended secrets to ${WRITE_FILE}" >&2
fi
